docker_build/bake_ci.hcl, lib/dl_core/dl_core_tests/conftest.py, lib/dl_core/dl_core_tests/db/conftest.py, lib/dl_core/dl_core_tests/unit/conftest.py
For example, `pytest-asyncio` is in dev dependencies at the moment, and it is needed for tests => it is needed in CI
=> Install dev dependencies in CI to fix some tests

.github/workflows/main.yml, lib/dl_api_lib/dl_api_lib_tests/db/data_api/result/test_markup.py, metapkg/poetry.lock, metapkg/pyproject.toml
Adding workflow to run code quality checks
=> ci: add code quality workflow

.github/.scripts/gh_pull_request_check_label.sh, .github/.scripts/gh_user_check_permission.sh, .github/.scripts/git_config_save_directory.sh, .github/workflows/main.yml
Preventing main CI to start for users with read rights or less.
Adding label support for workflow:
ci-approved: if PR is labeled, workflow will work no matter the user created PR
If commit is pushed to the branch, label will be dropped
tests-force-skipped: if PR is labeled, workflow will skip tests and mark test-results job as green ignoring results
test-results job will soon become required for merge
Changing trigger to pull_request_target to allow fork PRs to use write permissions
=> BI-5174: Add skip-tests and ci-allowed labels support for main workflow

lib/dl_task_processor/dl_task_processor/arq_wrapper.py, lib/dl_task_processor/dl_task_processor/state.py, lib/dl_task_processor/dl_task_processor/task.py, lib/dl_task_processor/dl_task_processor/upstream_worker.py, lib/dl_task_processor/dl_task_processor/worker.py, lib/dl_task_processor/dl_task_processor_tests/db/conftest.py, lib/dl_task_processor/dl_task_processor_tests/db/test_health_check.py, lib/dl_task_processor/dl_task_processor_tests/utils.py, pyproject.toml
Suppose concurrent job limit is 10 and health check interval is 30s.
If the worker takes 10 tasks from the queue and all of them are processed for longer than 31s, the worker is as good as dead to the outside world:
- the health check record is deleted due to [this ttl](https://github.com/samuelcolvin/arq/blob/ab2dda2011ab27007650c4918d3704f3bf7ac13d/arq/worker.py#L771)
- [this semaphore](https://github.com/samuelcolvin/arq/blame/9109c2e59d2b13fa59d246da03d19d7844a6fa19/arq/worker.py#L377) won't allow the health check record to be set on the next iteration of the main loop (this is fixed in upstream, so we bring it here due to the lack of arq releases)
=> BI-5191, BI-5192 Parametrize HC ttl in ArqWorker; include semaphore fixes from upstream; some mypy

lib/dl_api_commons/dl_api_commons/aiohttp/aiohttp_client.py, lib/dl_api_lib_testing/dl_api_lib_testing/base.py, lib/dl_configs/dl_configs/utils.py, lib/dl_connector_bitrix_gds/dl_connector_bitrix_gds/core/connection_executors.py, lib/dl_connector_bitrix_gds/dl_connector_bitrix_gds/core/target_dto.py, lib/dl_connector_bundle_chs3/dl_connector_bundle_chs3/chs3_base/core/connection_executors.py, lib/dl_connector_bundle_chs3/dl_connector_bundle_chs3/chs3_base/core/target_dto.py, lib/dl_connector_bundle_chs3/dl_connector_bundle_chs3_tests/db/base/core/base.py, lib/dl_connector_bundle_chs3/dl_connector_bundle_chs3_tests/db/conftest.py, lib/dl_connector_chyt/dl_connector_chyt/core/connection_executors.py, lib/dl_connector_clickhouse/dl_connector_clickhouse/core/clickhouse/testing/exec_factory.py, lib/dl_connector_clickhouse/dl_connector_clickhouse/core/clickhouse_base/connection_executors.py, lib/dl_connector_clickhouse/dl_connector_clickhouse/core/clickhouse_base/target_dto.py, lib/dl_connector_promql/dl_connector_promql/core/connection_executors.py, lib/dl_connector_promql/dl_connector_promql/core/target_dto.py, lib/dl_core/dl_core/connection_executors/adapters/async_adapters_aiohttp.py, lib/dl_core/dl_core/connection_executors/common_base.py, lib/dl_core/dl_core/connection_executors/models/connection_target_dto_base.py, lib/dl_core/dl_core/services_registry/conn_executor_factory.py, lib/dl_core/dl_core/services_registry/conn_executor_factory_base.py, lib/dl_core/dl_core/services_registry/sr_factories.py, lib/dl_core/dl_core_tests/conftest.py, lib/dl_core/dl_core_tests/db/compeng/test_compeng_cache.py, lib/dl_core_testing/dl_core_testing/testcases/service_base.py, lib/dl_file_uploader_api_lib/dl_file_uploader_api_lib_tests/conftest.py, lib/dl_file_uploader_worker_lib/dl_file_uploader_worker_lib_tests/conftest.py
For https://github.com/datalens-tech/datalens-backend/issues/233
Pass root certificates to ConnExecutors and use them in AioHttp-based adapters.
Important notes:
1. Pass ca_data to rqe in conn_target_dto. Certificates can take up a lot of space (up to 300 kilobytes), but this method ensures the use of the same certificates in RQE as in the API. Perhaps we should compress data when communicating with RQE.
2. Change `root_certificates` fixtures scope to `session` (thanks @ovsds)
3. Decode `ca_data` as `ASCII`, not `Unicode`, because the data is stored in PEM format
=> Use root ca explicitly in http-based adapters

lib/dl_connector_clickhouse/dl_connector_clickhouse/core/clickhouse_base/adapters.py, lib/dl_core/dl_core/connection_executors/adapters/adapters_base.py, lib/dl_core/dl_core/connection_executors/adapters/async_adapters_aiohttp.py, lib/dl_core/dl_core/connection_executors/adapters/async_adapters_base.py, lib/dl_core/dl_core/connection_executors/adapters/async_adapters_remote.py
Switched action initialization to using `__attrs_post_init__` because otherwise action factories do not have access to other attrs fields.
=> Fixed initialization of adapter actions (via attrs post-init)

lib/dl_api_connector/dl_api_connector/api_schema/connection_base.py, lib/dl_connector_clickhouse/dl_connector_clickhouse/core/clickhouse/us_connection.py, lib/dl_core/dl_core/us_connection_base.py
Minor extension for connection options.
Added the `allow_selector` to supported query types. This will tell frontend whether this query type supports selectors or not (some query types should only be used for charts, others for query editor suggestions, etc.)
=> Added query_type allow_selector flag to connector options

lib/dl_api_lib/dl_api_lib/app/data_api/resources/ping.py, lib/dl_compeng_pg/dl_compeng_pg/compeng_aiopg/data_processor_service_aiopg.py, lib/dl_compeng_pg/dl_compeng_pg/compeng_aiopg/processor_aiopg.py, lib/dl_compeng_pg/dl_compeng_pg/compeng_asyncpg/data_processor_service_asyncpg.py, lib/dl_compeng_pg/dl_compeng_pg/compeng_asyncpg/processor_asyncpg.py, lib/dl_core/dl_core/aio/web_app_services/data_processing/data_processor.py, lib/dl_core/dl_core/data_processing/cache/processing_helper.py, lib/dl_core/dl_core/data_processing/dashsql.py, lib/dl_core/dl_core/data_processing/processing/cache/exec_adapter.py, lib/dl_core/dl_core/data_processing/processing/cache/processor.py, lib/dl_core/dl_core/data_processing/processing/db_base/exec_adapter_base.py, lib/dl_core/dl_core/data_processing/processing/processor.py, lib/dl_core/dl_core/data_processing/processing/source_db/processor.py, lib/dl_core/dl_core/data_processing/processing/source_db/selector_exec_adapter.py, lib/dl_core/dl_core/services_registry/data_processor_factory.py, lib/dl_core/dl_core_tests/db/compeng/test_pg_op_exec_adapter.py, lib/dl_core/dl_core_tests/db/compeng/test_pg_op_processor.py
To remove some interconnectedness of our core code.
The initial motivation was to remove `service_registry` from `CacheProcessingHelper` so that it can be moved to the `dl_cache_engine` package. But I decided to go a step further.
=> Removed service registry usage from data processors

lib/dl_api_lib/dl_api_lib/app/data_api/resources/typed_query.py, lib/dl_api_lib/dl_api_lib/service_registry/service_registry.py, lib/dl_api_lib/dl_api_lib/service_registry/typed_query_processor_factory.py
For adding cached processor creation in the near future. This logic should be isolated from the handler
=> Implemented typed query processor factories in SR

lib/dl_api_lib/dl_api_lib_tests/db/data_api/result/complex_queries/test_ext_agg_basic.py, lib/dl_query_processing/dl_query_processing/multi_query/splitters/mask_based.py
There seems to be no reason for such restriction, as one can safely use complex expressions in `JOIN ON` clause. Moreover, it is possible under a specific set of circumstances to achieve a situation where such clause is required (see a test for example).
=> BI-5359: remove an erroneous type check on making a join expression

lib/dl_api_lib/dl_api_lib/error_handling.py, lib/dl_connector_bigquery/dl_connector_bigquery/core/adapters.py, lib/dl_connector_bigquery/dl_connector_bigquery/core/sa_types.py, lib/dl_connector_bigquery/dl_connector_bigquery/core/type_transformer.py, lib/dl_connector_bigquery/dl_connector_bigquery_tests/ext/api/base.py, lib/dl_connector_bigquery/dl_connector_bigquery_tests/ext/api/test_connection.py, lib/dl_core/dl_core/exc.py
Also semi-fix test table setup (user type map, sqlalchemy types)
Also, there are a bunch of failing tests (e.g. `TestBigQueryDataCache` and most of `api/`), that could never be green because of the issues above and this https://github.com/datalens-tech/datalens-backend/blob/d467d405fafc7a17f113892f11a9f711e3d8cc2a/lib/dl_api_lib_testing/dl_api_lib_testing/helpers/data_source.py#L8-L8 comment in addition (data sources with connector specific fields can't be constructed properly)
=> fix(connectors): BI-5777 handle google api errors & bad creds error in BQ connector

lib/dl_api_lib/dl_api_lib_tests/db/data_api/result/complex_queries/test_ext_agg_basic.py, lib/dl_api_lib/dl_api_lib_tests/db/data_api/result/complex_queries/test_lookup_functions.py, lib/dl_formula/dl_formula/core/nodes.py, lib/dl_formula/dl_formula/mutation/lod.py, lib/dl_formula/dl_formula/mutation/window.py, lib/dl_formula/dl_formula_tests/unit/mutation/test_optimization.py, lib/dl_query_processing/dl_query_processing/compilation/formula_compiler.py
Currently, mutations apply to a node first and to its children second. This results in the following bug: expressions like `if 1=1 then expr1 else expr2` are simplified to` if 1 then expr1 else expr2` because `1=1` doesn't constitute as a constant literal when applying the if-case optimization, but they can be further simplified to just `expr1`.
We should apply mutations to children first, in this case we will first optimize `1=1` and only then the if expression.
This is the second attempt after https://github.com/datalens-tech/datalens-backend/pull/384. In this attempt, we separate `RemapBfbMutation` from the rest of pre-substitution mutations because it conflicts with `LookupDefaultBfbMutation`, resulting in erroneous results for `AGO` and `AT_DATE` functions.
=> fix: BI-5359 apply mutations to node's children before the node itself

lib/dl_api_lib/dl_api_lib_tests/db/data_api/result/complex_queries/test_ext_agg_basic.py, lib/dl_query_processing/dl_query_processing/multi_query/splitters/query_fork.py
As a consequence of https://github.com/datalens-tech/datalens-backend/pull/620, it is now possible that when we are normalizing join nodes, we erroneously replace the child node instead of a parent. To resolve this, we should apply replacements one by one, and check for more complex replacements first. This way parent replacements would occur first.
=> fix: BI-5359 fix joining node normalization

lib/dl_api_lib_testing/dl_api_lib_testing/client.py
In Werkzeug 3.0 `server_name` argument was removed in `set_cookie` and `delete_cookie` methods
=> test: BI-0 update werkzeug testing utils for the new version

lib/dl_auth_api_lib/dl_auth_api_lib_tests/ext/test_snowflake.py
The error that we receive from snowflake in case of invalid account has changed once again
=> test(connectors): BI-0 fix snowflake auth test once again

lib/dl_connector_metrica/dl_connector_metrica_tests/ext/api/test_data.py
The current filter started to cause the following error
```
Date of beginning or end of accounting period entered incorrectly, value: 2019-12-01, limit: 2021-02-01, error code: 4005
```
=> test(connectors): BI-0 update filter in metrica tests

lib/dl_api_lib/dl_api_lib_tests/db/data_api/result/complex_queries/test_window_functions.py, lib/dl_query_processing/dl_query_processing/compilation/formula_compiler.py
This change should also be virtually free in terms of performance thanks to stage caching https://github.com/datalens-tech/datalens-backend/blob/62ce5bf2b9a8f1d22c4a1342f72629037708dc28/lib/dl_query_processing/dl_query_processing/compilation/formula_compiler.py#L283-L290
=> fix(formula): BI-5959 apply mutations before adding formula to global dimensions during validation

lib/dl_core/dl_core/us_manager/us_entry_serializer.py, lib/dl_core/dl_core/us_manager/us_manager.py
Reverts datalens-tech/datalens-backend#774
=> revert: BI-0 https://github.com/datalens-tech/datalens-backend/pull/774

lib/dl_connector_oracle/dl_connector_oracle_tests/db/core/test_connection_executor.py, lib/dl_core_testing/dl_core_testing/csv_table_dumper.py
Some DBMS do not support case-sensitive table names at all (MySQL is an example). However, using lowercase table names is always a good practice.
=> test: BI-0 Force table name to be generated in lowercase in CsvTableDumper

lib/dl_connector_trino/dl_connector_trino/core/adapters.py, lib/dl_connector_trino/dl_connector_trino/core/us_connection.py, lib/dl_connector_trino/dl_connector_trino_tests/db/core/test_connection.py
This is important because `conn_executor._extract_sync_sa_adapter` hack doesn't work for RQE
=> fix: BI-5355 Move Trino get_catalogs query from adapter to us_connection

lib/dl_connector_bundle_chs3/dl_connector_bundle_chs3/chs3_base/api/api_schema/connection.py, lib/dl_connector_bundle_chs3/dl_connector_bundle_chs3/chs3_base/core/us_connection.py, lib/dl_file_uploader_api_lib/dl_file_uploader_api_lib/app.py, lib/dl_file_uploader_api_lib/dl_file_uploader_api_lib/views/sources.py
NOTE: these changes must be deployed in two passes – first file-uploader-api and then control-api
=> fix(connectors): BI-6252 disable user auth for Preview & InternalParams in fu-api

lib/dl_api_lib/dl_api_lib/app/control_api/resources/dataset.py, lib/dl_api_lib/dl_api_lib/app/data_api/resources/dataset/base.py, lib/dl_api_lib/dl_api_lib/app/data_api/resources/dataset/distinct.py, lib/dl_api_lib/dl_api_lib/app/data_api/resources/dataset/pivot.py, lib/dl_api_lib/dl_api_lib/app/data_api/resources/dataset/range.py, lib/dl_api_lib/dl_api_lib/app/data_api/resources/dataset/result.py, lib/dl_core/dl_core/us_manager/us_entry_serializer.py, lib/dl_core/dl_core/us_manager/us_manager.py, lib/dl_core/dl_core/us_manager/us_manager_async.py, lib/dl_core/dl_core/us_manager/us_manager_sync.py
Feature explaination:
When mutations cache is used, dataset is being deserialized twice. 
First - in [resolve_entities decorator](https://github.com/datalens-tech/datalens-backend/blob/0be009e18142fd17e24ff7ff2fd5bcd767a9d6ca/lib/dl_api_lib/dl_api_lib/app/data_api/resources/dataset/base.py#L178) inside [us manager get_by_id](https://github.com/datalens-tech/datalens-backend/blob/0be009e18142fd17e24ff7ff2fd5bcd767a9d6ca/lib/dl_core/dl_core/us_manager/us_manager_async.py#L148) 
Second - in [prepare_dataset_for_request](https://github.com/datalens-tech/datalens-backend/blob/0be009e18142fd17e24ff7ff2fd5bcd767a9d6ca/lib/dl_api_lib/dl_api_lib/app/data_api/resources/dataset/base.py#L288) when deserializing object from cache.
In real world case, deserialization may take up to 300 (or more) …
=> feat(optimization): BI-5933 avoid double deserialization for cached datasets

lib/dl_api_client/dl_api_client/dsmaker/api/data_api.py, lib/dl_api_lib/dl_api_lib/app/data_api/resources/dataset/base.py, lib/dl_api_lib/dl_api_lib_tests/db/data_api/result/test_revision.py, lib/dl_api_lib_testing/dl_api_lib_testing/data_api_base.py
Unlike the [control-api](https://github.com/datalens-tech/datalens-backend/pull/865), the dataset revision_id substitution is not required here. It is expected that the revision_id of the dataset received by revId and the revision_id from the req_model match.
=> feat: BI-6218 rev_id query param for data-api

lib/dl_file_uploader_api_lib/dl_file_uploader_api_lib/data_file_preparer.py
Full list of allowed domains
These were always there:
- `disk.yandex.ru`
- `disk.yandex.az`
- `disk.yandex.by`
- `disk.yandex.co.il`
- `disk.yandex.com`
- `disk.yandex.com.am`
- `disk.yandex.com.ge`
- `disk.yandex.com.tr`
- `disk.yandex.ee`
- `disk.yandex.fr`
- `disk.yandex.kg`
- `disk.yandex.kz`
- `disk.yandex.lt`
- `disk.yandex.lv`
- `disk.yandex.md`
- `disk.yandex.tj`
- `disk.yandex.tm`
- `disk.yandex.uz`
These were added recently:
- `disk.360.yandex.ru`
- `disk.360.yandex.az`
- `disk.360.yandex.by`
- `disk.360.yandex.co.il`
- `disk.360.yandex.com`
- `disk.360.yandex.com.am`
- `disk.360.yandex.com.ge`
- `disk.360.yandex.com.tr`
- `disk.360.yandex.ee`
- `disk.360.yandex.fr`
- `disk.360.yandex.kg`
- `disk.360.yandex.kz`
- `disk.360.yandex.lt`
- `disk.360.yandex.lv`
- `disk.360.yandex.md` …
=> feat(connectors): BI-6326 expand the list of allowed yadocs domains
