- lib/dl_core/dl_core/data_processing/cache/engine.py
This reverts commit 03a5b8a6e69591e5e896dc8d800c2545a53d5a60.
> Revert "Separated CacheKeyBuilder from EntityCacheEngineBase (#33)"

- docker_build/target_dl_base_linux_w_db_bin_dependencies/scripts/002-add-repos.sh
- docker_build/target_dl_base_linux_w_db_bin_dependencies/scripts/300-db-libs.sh
See https://github.com/datalens-tech/datalens-backend/issues/201
> Pin MSSQL package versions

- lib/dl_api_connector/dl_api_connector/api_schema/connection_base.py
- lib/dl_api_lib/dl_api_lib/app/control_api/resources/connections.py
- lib/dl_api_lib_testing/dl_api_lib_testing/connector/connection_suite.py
- lib/dl_constants/dl_constants/enums.py
- lib/dl_core/dl_core/us_connection_base.py
Also cleaned up some connection-related legacy.
> Added `options` section to connection GET api handler response

- lib/dl_api_lib/dl_api_lib/pivot/native/data_frame.py
- lib/dl_api_lib/dl_api_lib/pivot/native/facade.py
- lib/dl_api_lib/dl_api_lib/pivot/native/paginator.py
- lib/dl_api_lib/dl_api_lib/pivot/native/sorter.py
- lib/dl_api_lib/dl_api_lib/pivot/native/transformer.py
- lib/dl_api_lib/dl_api_lib/pivot/pandas/sorter.py
- lib/dl_api_lib/dl_api_lib/pivot/primitives.py
- lib/dl_api_lib/dl_api_lib/pivot/sort_helpers.py
- lib/dl_api_lib/dl_api_lib/pivot/sort_strategy.py
At the moment measure sorting is not implemented, so all the related tests fail when switching to the native version
> Added a partial native (pure Python) implementation of the pivot engine

- lib/dl_connector_mysql/dl_connector_mysql_tests/db/core/test_connection_executor.py
Replace for
https://github.com/aio-libs/aiomysql/blob/83aa96e12b1b3f2bd373f60a9c585b6e73f40f52/aiomysql/sa/result.py#L253
The ResultProxy._prepare creates destructor for an internal cursor object by `self._weak = weakref.ref(self, callback)`. However, there's an issue where it attempts to execute a task in a potentially closed event loop, leading to strange behavior:
1. Datalens reads all data from ReadProxy and finishes the test
2. fixture event_loop closes the loop
3. GC deletes old objects -> runs weakref's callbacks
2. the cursor's callback creates coroutine Cursor.close
3. the cursor's callback tries to run this coroutine in the old loop (2)
4. the old loop generates exception, but the coroutine is still here
5. asyncio generates warning
5. aiohttp-pytest-plugin transforms warning to …
> Mock ResultProxy._prepare in aiomysql tests

- app/dl_control_api/Dockerfile
- app/dl_data_api/Dockerfile
> Switch to a non-root user in docker

- lib/dl_file_uploader_worker_lib/dl_file_uploader_worker_lib/app.py
- lib/dl_task_processor/dl_task_processor/worker.py
Adding a point of extension from where worker metrics can be sent to wherever one can send them
> BI-5193 File uploader worker metrics sender

- lib/dl_dashsql/dl_dashsql/exc.py
- lib/dl_dashsql/dl_dashsql/formatting/shortcuts.py
- lib/dl_dashsql/dl_dashsql/typed_query/primitives.py
Extended the dashsql primitives a little to simplify usage of query parameters
> Minor additions to dashql primitives

- lib/dl_connector_chyt/dl_connector_chyt/core/async_adapters.py
Added logging of CHYT headers for easier troubleshooting
> Added logging of CHYT data query response headers

- lib/dl_api_lib/dl_api_lib/app/data_api/resources/typed_query.py
- lib/dl_api_lib/dl_api_lib/schemas/typed_query.py
- lib/dl_api_lib/dl_api_lib_tests/db/data_api/test_typed_query.py
- lib/dl_api_lib_testing/dl_api_lib_testing/connector/typed_query_suite.py
- lib/dl_connector_clickhouse/dl_connector_clickhouse/core/clickhouse/us_connection.py
- lib/dl_connector_clickhouse/dl_connector_clickhouse/core/clickhouse_base/adapters.py
- lib/dl_core/dl_core/connection_executors/adapters/adapter_actions/typed_query.py
- lib/dl_dashsql/dl_dashsql/typed_query/primitives.py
Adding data types to the new typed query interface (without them it's kind of useless)
> Added user data types to typed query result

- lib/dl_core/dl_core_tests/db/test_typed_query.py
- lib/dl_core_testing/dl_core_testing/testcases/typed_query.py
Adding some core-level tests for the typed query interface
> Added typed query core-level tests

- lib/dl_api_connector/dl_api_connector/api_schema/connection_base.py
- lib/dl_api_lib/dl_api_lib/app/control_api/resources/connections.py
- lib/dl_api_lib/dl_api_lib/app/data_api/resources/typed_query.py
- lib/dl_api_lib/dl_api_lib/schemas/typed_query.py
- lib/dl_api_lib_testing/dl_api_lib_testing/connector/connection_suite.py
- lib/dl_connector_clickhouse/dl_connector_clickhouse/core/clickhouse/us_connection.py
- lib/dl_constants/dl_constants/enums.py
- lib/dl_core/dl_core/us_connection_base.py
A small update of the new typed_query API, added some new attributes to connection options (to control the behaviour of the typed_query API)
> Some fixes for the typed_query api

- lib/dl_api_lib/dl_api_lib/app/data_api/resources/typed_query.py
- lib/dl_core/dl_core/data_processing/typed_query.py
- lib/dl_dashsql/dl_dashsql/typed_query/processor/base.py
A new abstraction layer for processing typed queries. This is where caches will go in the future
> Added typed query processor

- lib/dl_api_connector/dl_api_connector/api_schema/connection_base.py
- lib/dl_core/dl_core/us_connection_base.py
- lib/dl_core_testing/dl_core_testing/connector.py
Removing a useless mixin that only complicates code
> Removing ExecutorBasedMixin. Part 1

- lib/dl_api_lib/dl_api_lib/app_settings.py
Loading of these settings from yaml does not work at the moment
> Fixed pivot and query mode settings

- lib/dl_api_lib/dl_api_lib/app_settings.py
Reverts datalens-tech/datalens-backend#346
> Revert "Fixed pivot and query mode settings"

- terrarium/dl_gitmanager/dl_gitmanager/scripts/gitmanager_cli.py
- terrarium/dl_repmanager/dl_repmanager/dependency_resolution.py
- terrarium/dl_repmanager/dl_repmanager/package_index.py
- terrarium/dl_repmanager/dl_repmanager/primitives.py
- terrarium/dl_repmanager/dl_repmanager/repository_navigator.py
- terrarium/dl_repmanager/dl_repmanager/scripts/repmanager_cli.py
Implemented deep dependency resolution in repmanager for use in CI workflows
> Added deep dependency resolution logic to repmanager

- lib/dl_api_lib/dl_api_lib/loader.py
- lib/dl_pivot/dl_pivot/plugin_registration.py
Otherwise it's impossible to use non-default pivot engine in settings
> Added preloading of pivot engine plugins

- lib/dl_core/dl_core/data_processing/processing/db_base/op_executors.py
- lib/dl_core/dl_core/data_processing/processing/source_db/selector_exec_adapter.py
- lib/dl_core/dl_core/data_processing/streaming.py
- lib/dl_core/dl_core_tests/unit/data_processing/test_streaming.py
To remove dl_core dependency from the `serialization` module
> Parameterized AsyncChunkedLimited with exception type

- lib/dl_api_lib/dl_api_lib/app/control_api/app.py
- lib/dl_api_lib/dl_api_lib/app/data_api/resources/dashsql.py
- lib/dl_api_lib/dl_api_lib/app/data_api/resources/dataset/base.py
- lib/dl_api_lib/dl_api_lib/app_common_settings.py
- lib/dl_connector_bitrix_gds/dl_connector_bitrix_gds/core/us_connection.py
- lib/dl_connector_chyt/dl_connector_chyt/core/us_connection.py
- lib/dl_connector_metrica/dl_connector_metrica/core/us_connection.py
- lib/dl_core/dl_core/data_processing/cache/utils.py
- lib/dl_core/dl_core/data_processing/dashsql.py
- lib/dl_core/dl_core/data_processing/processing/source_db/selector_exec_adapter.py
- lib/dl_core/dl_core/services_registry/conn_executor_factory.py
- lib/dl_core/dl_core/services_registry/conn_executor_factory_base.py
- lib/dl_core/dl_core/services_registry/sr_factories.py
- lib/dl_core/dl_core/services_registry/typing.py
- lib/dl_core/dl_core/us_connection_base.py
- lib/dl_core_testing/dl_core_testing/dataset.py
- lib/dl_file_uploader_task_interface/dl_file_uploader_task_interface/utils_service_registry.py
Removing deprecated connection mixin.
> Removing ExecutorBasedMixin. Part 2

- lib/dl_us_client/dl_us_client/constants.py
Adding new possible operation codes for united storage client
> Add existing operation codes for us client

- lib/dl_api_lib/dl_api_lib/app/data_api/resources/typed_query.py
- lib/dl_api_lib/dl_api_lib/schemas/typed_query.py
- lib/dl_api_lib/dl_api_lib/service_registry/typed_query_processor_factory.py
- lib/dl_api_lib/dl_api_lib_tests/db/data_api/test_typed_query.py
- lib/dl_core/dl_core/connection_executors/adapters/adapter_actions/typed_query.py
- lib/dl_core_testing/dl_core_testing/testcases/typed_query.py
- lib/dl_dashsql/dl_dashsql/formatting/shortcuts.py
- lib/dl_dashsql/dl_dashsql/typed_query/primitives.py
- lib/dl_dashsql/dl_dashsql/typed_query/processor/cache.py
- lib/dl_dashsql/dl_dashsql/typed_query/query_serialization.py
- lib/dl_dashsql/dl_dashsql/typed_query/result_serialization.py
- lib/dl_dashsql/pyproject.toml
Caching for the new typed_query API (dashsql selectors and queries)
> Implemented CachedTypedQueryProcessor

- terrarium/bi_ci/bi_ci/execute_mypy_multi.py
- terrarium/dl_repmanager/pyproject.toml
Attempt to speed up mypy checks.
This pull request adds the ability to run mypy in parallel on multiple projects independently, while reusing the mypy cache on the file system as much as possible.
> Run mypy in parallel

- lib/dl_api_lib/dl_api_lib_tests/db/data_api/result/test_markup.py
- lib/dl_formula/dl_formula/definitions/functions_markup.py
- lib/dl_formula_testing/dl_formula_testing/testcases/functions_markup.py
https://github.com/datalens-tech/datalens/issues/92
> BI-5273 Markup image fix

- lib/dl_api_commons/dl_api_commons/__init__.py
- lib/dl_api_commons/dl_api_commons/aio/middlewares/request_id.py
- lib/dl_api_commons/dl_api_commons/flask/middlewares/request_id.py
- lib/dl_api_commons/dl_api_commons/logging.py
- lib/dl_api_commons/dl_api_commons/logging_sentry.py
- lib/dl_api_commons/dl_api_commons_tests/unit/aio/test_common_logging.py
- lib/dl_api_lib/dl_api_lib/aio/middlewares/json_body_middleware.py
- lib/dl_api_lib/dl_api_lib/api_decorators.py
- lib/dl_core/dl_core/united_storage_client.py
- lib/dl_core/dl_core/utils.py
This will allow the re-definition/customization of secret headers, cookies, etc.
> Moved some request logging tools to classes to enable their customization

- lib/dl_connector_mysql/dl_connector_mysql/core/async_adapters_mysql.py
Reverts datalens-tech/datalens-backend#389
> Revert "BI-5267 Readonly transaction in MySQL connector"

- .github/workflows/main.yml
- lib/dl_connector_bitrix_gds/docker-compose/Dockerfile.db-postgres-13
- lib/dl_connector_clickhouse/docker-compose/Dockerfile.db-clickhouse-21-8
- lib/dl_connector_greenplum/docker-compose/Dockerfile.db-postgres-13
- lib/dl_connector_postgresql/docker-compose/Dockerfile.db-postgres-13
- lib/dl_sqlalchemy_postgres/docker-compose.yml
- lib/testenv-common/images/Dockerfile.pg-us
Real Checks with new workflow:
https://github.com/datalens-tech/datalens-backend/actions/runs/9321134102
> build: replace mirrored images from docker hub

- docker_build/_bake_vars_functions.hcl
- docker_build/bake_apps.hcl
- docker_build/bake_base.hcl
- docker_build/bake_sources.hcl
This way one may reuse base targets while overriding sources layer
> Add points of extension to bake files

- lib/clickhouse-sqlalchemy/clickhouse_sqlalchemy/drivers/base.py
Backport for https://github.com/xzkostyan/clickhouse-sqlalchemy/pull/94
> Fix DROP in clickhouse-sqlalchemy

- app/app_configs/api.yaml
- app/dl_control_api/pyproject.toml
- app/dl_data_api/pyproject.toml
- docker_build/target_base_jammy_db/Dockerfile
- metapkg/poetry.lock
https://github.com/datalens-tech/datalens/issues/5
> feat(connectors): BI-5232 enable MSSQL connector

- tools/taskfiles/taskfile_dev.yml
…mes and orphans removal, added compose-show-logs task
> ci: BI-0 Build option to compose up, down with volumes and orphans removal, compose-show-logs task

- lib/dl_formula_testing/dl_formula_testing/testcases/base.py
- lib/dl_formula_testing/dl_formula_testing/testcases/conditional_blocks.py
> test: BI-0 data_table optional schema support

- lib/dl_core/dl_core/components/accessor.py
- lib/dl_core/dl_core/components/editor.py
- lib/dl_core/dl_core/components/ids.py
- lib/dl_core/dl_core/data_source/base.py
- lib/dl_core/dl_core/data_source/collection.py
- lib/dl_core/dl_core/data_source/sql.py
- lib/dl_core/dl_core/data_source/type_mapping.py
- lib/dl_core/dl_core/data_source/utils.py
- lib/dl_core/dl_core/data_source_spec/__init__.py
- lib/dl_core/dl_core/data_source_spec/base.py
- lib/dl_core/dl_core/data_source_spec/collection.py
- lib/dl_core/dl_core/data_source_spec/sql.py
- lib/dl_core/dl_core/data_source_spec/type_mapping.py
dropping unnesessary typing imports and `from __future__ import annotations`
> refactor: BI-6073 preliminary refactor

- .github/workflows/main.yml
Failing CI are fixed by this PR, but changes will be applied only after merge. 
Run using new version:
https://github.com/datalens-tech/datalens-backend/actions/runs/14190615757/job/39754335807
> ci: BI-0 main.yaml fix lost sha

- lib/dl_connector_postgresql/dl_connector_postgresql/formula/definitions/functions_array.py
- lib/dl_connector_postgresql/dl_connector_postgresql_tests/db/formula/test_functions_array.py
- lib/dl_connector_postgresql/dl_connector_postgresql_tests/db/formula/test_operators.py
- lib/dl_formula_testing/dl_formula_testing/evaluator.py
- lib/dl_formula_testing/dl_formula_testing/table.py
- lib/dl_formula_testing/dl_formula_testing/testcases/functions_array.py
Changes:
- Add more tests for formula
- Mask some tests as xfail for fix in future
- Fix behavior of PostgreSQL LEN and COUNT_ITEM for arrays
- Handle NULL argument as NULL result
- Handle empty array argument
> fix(connectors): BI-6120 fix postgres COUNT_ITEM and LEN

- app/dl_data_api/etc/service/dl_api/run
> fix: BI-0 fix gunicorn app module in data-api run script

- lib/dl_connector_bundle_chs3/dl_connector_bundle_chs3/chs3_base/core/testing/utils.py
- lib/dl_connector_bundle_chs3/dl_connector_bundle_chs3/chs3_base/core/us_connection.py
- lib/dl_connector_clickhouse/dl_connector_clickhouse/core/clickhouse/us_connection.py
- lib/dl_connector_clickhouse/dl_connector_clickhouse/core/clickhouse_base/us_connection.py
- lib/dl_connector_greenplum/dl_connector_greenplum/core/us_connection.py
- lib/dl_connector_mssql/dl_connector_mssql/core/us_connection.py
- lib/dl_connector_mysql/dl_connector_mysql/core/us_connection.py
- lib/dl_connector_oracle/dl_connector_oracle/core/us_connection.py
- lib/dl_connector_postgresql/dl_connector_postgresql/core/postgresql/us_connection.py
- lib/dl_core/dl_core/connection_models/dto_defs.py
See https://github.com/python-attrs/attrs/issues/519#issuecomment-1878316651
> dev: BI-0 update typing for multihosts tuple to fix mypy

- lib/dl_connector_trino/dl_connector_trino/formula/definitions/operators_binary.py
> feat: BI-5355 Add untested binary operators to Trino

- lib/dl_api_lib_testing/dl_api_lib_testing/connector/connection_suite.py
- lib/dl_connector_bigquery/dl_connector_bigquery/core/us_connection.py
- lib/dl_connector_bitrix_gds/dl_connector_bitrix_gds/core/us_connection.py
- lib/dl_connector_bundle_chs3/dl_connector_bundle_chs3/chs3_base/core/us_connection.py
- lib/dl_connector_chyt/dl_connector_chyt/core/us_connection.py
- lib/dl_connector_greenplum/dl_connector_greenplum/core/us_connection.py
- lib/dl_connector_postgresql/dl_connector_postgresql/core/postgresql/us_connection.py
- lib/dl_connector_postgresql/dl_connector_postgresql/core/postgresql_base/us_connection.py
- lib/dl_connector_trino/dl_connector_trino/core/us_connection.py
TODO: need to test Snowflake separately, bc its tests are not enabled in CI
> feat(connectors): BI-5975 allow exports for more connectors

- lib/dl_api_connector/dl_api_connector/api_schema/top_level.py
- lib/dl_connector_bundle_chs3/dl_connector_bundle_chs3/chs3_base/api/api_schema/connection.py
- lib/dl_connector_ydb/dl_connector_ydb_tests/db/api/test_connection.py
Also removing `preview` from exports for file-based connectors
> feat(connectors): BI-6275 export fake secrets when they are set, null otherwise

- lib/dl_connector_bigquery/dl_connector_bigquery/core/data_source.py
- lib/dl_connector_chyt/dl_connector_chyt/core/data_source.py
- lib/dl_connector_oracle/dl_connector_oracle/core/data_source.py
- lib/dl_connector_snowflake/dl_connector_snowflake/core/data_source.py
- lib/dl_connector_ydb/dl_connector_ydb/core/ydb/data_source.py
- lib/dl_core/dl_core/data_source/base.py
- lib/dl_core_testing/dl_core_testing/testcases/data_source.py
fix and test that key is not empty
all other is just refactor
> fix: BI-6315 DataSource cache_key_part
